name: html_parser
version: 0.5.0
description: A fast and forgiving HTML parser for Dart.
authors:
  - Matan Lurey <matanl@google.com>
homepage: https://github.com/matanlurey/html_parser
dependencies:
  charcode: ">=1.1.0 <2.0.0"
  collection: "^2.0.0"
  string_scanner: "^1.0.0"
dev_dependencies:
  angular2:
  benchmark_harness:
  dart_style:
  html:
  test:
